# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: loyalty-campaigns test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      working-directory: loyalty-campaigns
    - name: Authenticate with GitHub package registry
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
    - name: NPM CI
      run: npm ci
      working-directory: loyalty-campaigns
    - name: Build
      run: npm run build --if-present
      working-directory: loyalty-campaigns
    - name: Test
      run: npm test
      env:
        CI: true
      working-directory: loyalty-campaigns